### PR TITLE
Rails 7 Support

### PR DESCRIPTION
**Pull request by BilalBudhani**

### CODE REVIEW

**Comment by pmviva** [comment]
Why moving all dev and test dependencies from main gemspec to the several gemfiles? seems redundant to declare all the dependencies in all files

**Comment by azeemh** [comment]
Hi, this is exciting work. Please let me know how to help out. This is the only thing stopping me from updating my platform to rails 7. (I currently use it in rails 5)

Thank you so much and I look forward to the release!

**Comment by pmviva** [comment]
Hi, thanks for the feedback on the project. Regarding support for rails 7, i wanted to mention that I am not actually developing in ruby since a few years, and I don't have much spare time to invest in supporting this and the other three companion frameworks.

You could create a new PR with support for rails 7 and I can look at it and merge it. Sine i do not have time to keep up with further releases I was planning sooner or later deprecating this framework or transfer the ownership of the project to another developer who interested in maintain it.

Thanks Pablo

**Review by azeemh — APPROVED** [review]

**Review by azeemh — APPROVED** [review]

**Comment by azeemh** [comment]
i updated my gemfile for now and this doesn't have any `bundle` conflicts anymore. 

```
#mention system gem -- updated for rails 7+
#gem 'mention_system'
gem 'mention_system', git: 'https://github.com/BilalBudhani/mention_system/', branch: 'rails-7'
```

**Comment by BilalBudhani** [comment]
> Why moving all dev and test dependencies from main gemspec to the several gemfiles? seems redundant to declare all the dependencies in all files

Thanks for the feedback. I moved all the dependencies to `gemspec`. I have also added CI to check against important versions of Rails. 

> You could create a new PR with support for rails 7 and I can look at it and merge it. Sine i do not have time to keep up with further releases I was planning sooner or later deprecating this framework or transfer the ownership of the project to another developer who interested in maintain it.

@pmviva Since I'm using this gem in a couple of my projects, I'm interested in taking it over and keeping the development going. Let me know what you think.

**Comment by pmviva** [comment]
Sure, we can discuss you taking over the project and supporting it from now
on if you have the time and will

**Comment by BilalBudhani** [comment]
Sure thing. Meanwhile, Please merge this PR if everything looks good.

**Review by pmviva — APPROVED** [review]
LGTM

**Comment by pmviva** [comment]
The PR is already merged, I can add you as owner of the project in rubygems so you can release a new version of the gem, since I do not have my ruby environment setup as of now.

**Comment by BilalBudhani** [comment]
@pmviva sounds good. My username on Rubygems.org is the same as Github.

**Comment by BilalBudhani** [comment]
I have released `0.3.0` version on Rubygems.org

@pmviva Can you add my commit access to this repo so I can push release related changes to master?

**Pull request merged**
